### ISSUE TITLE
(0, 0) similarity

### ISSUE THREAD

**Issue by DomrinaV** [blingenf/copydetect#21]
Hello! While using the method described in your API "For advanced use cases", I have encountered some examples that give the "IndexError: index 1 is out of bounds for axis 0 with size 0" error when trying to highlight, [0,0] similarities and (array([], dtype=float64), array([], dtype=float64)) slices. It seems as if they are processed incorrectly by copydetect, since there are some similar lines in them. In case of solutions which have only one line (like "print(0)" in python) adding something (like "import numpy as np") to them helps. I would like to know whether this is a bug or your tool is supposed to work this way.

```
>>> fp6 = copydetect.CodeFingerprint("solution 2.py", 25, 1)
>>> fp8 = copydetect.CodeFingerprint("solution 4.py", 25, 1)
>>> token_overlap, similarities, slices = copydetect.compare_files(fp6, fp8)
>>> print(similarities, slices)
(0, 0) (array([], dtype=float64), array([], dtype=float64))
>>> code1, _ = copydetect.utils.highlight_overlap(fp1.raw_code, slices[0], ">>", "<<")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/copydetect/utils.py", line 163, in highlight_overlap
    hl_percent = np.sum(slices[1] - slices[0])/len(doc)
IndexError: index 1 is out of bounds for axis 0 with size 0
```

solution 2.py:

```
a1 = []  # new list
n = int(input())  # length of list
for i in range(n):  
    new_element = int(input())  # new element
    a1.append(new_element)  # 

    
b1 = [] # new list
m = int(input())  # length of list
for i in range(m):  
    new_element = int(input())  # new element
    b1.append(new_element)  # 

s1 = set(b1)
ans = []
for i in range(n):
    if a1[i] in s1:
        ans.append(a1[i])
        
print(ans)

```
solution 4.py:

```
n = int(input())
#writing something here#writing something here#writing something here
lst = []#writing something here#writing something here#writing something here
for i in range(n):#writing something here#writing something here
    lst.append(int(input()))#writing something here
m = int(input())

lst2 = []#writing something here
for i in range(m):#writing something here
    lst2.append(int(input()))#writing something here

set_int = set(lst).intersection(set(lst2))#writing something here
res_lst = []#writing something here
for i in range(n):#writing something here#writing something here#writing something here#writing something here
    if (lst[i] in set_int):#writing something here#writing something here
        res_lst.append(lst[i])#writing something here#writing something here#writing something here

print(res_lst)#writing something here#writing something here#writing something here#writing something here



```
the same also happens for the following solutions:

```
#include<bits/stdc++.h>

using namespace std;
#define forn(i, n) for(int i = 0; i < int(n); i++) 
#define f first	
#define s second
#define ll long long
#define db double
#define pb push_back
typedef pair<int, int> pii;

void inppp(){
    freopen("input.txt", "r", stdin);
    freopen("output.txt", "w", stdout);
}


const int M = 1e9 + 7;
const int MAXN = 1e3 + 5;


//double ans = 0;



int main() {
	inppp();
	//setprecision(12);
	double t = 1;
	//cin >> t;
	int n;
	cin >> n;
	vector<int> arr(n);
	for(int i = 0; i < n; i++)
		cin >> arr[i];
	sort(arr.begin(), arr.end());

	int c = 1;
	for(int i = 1; i < n; i++) {
		if(arr[i] - arr[i - 1] > 1) c = 0;
	}

	cout << c << endl;
	
	return 0;
}
```

```

#include <iostream>
#include <algorithm>
#include <vector>
#include <map>
#include <set>
#include <iomanip>
#include <fstream>
#include <cmath>

using namespace std;

int check(ifstream &fin, int n)
{
  vector<int> vec;
  int a;

  while(fin >> a)
    vec.push_back(a);

  sort(vec.begin(), vec.end());
  
  for (int i = 0; i < n-1; ++i)
  {
    if (!(abs(vec[i]-vec[i + 1]) <= 1))
      return 0;
  }

  return 1;
}

int main()
{
  ifstream fin("input.txt");
  ofstream fout("output.txt");

  int a0;

  if (fin >> a0)
    fout << check(fin, a0);

  fin.close();
  fout.close();
  
  return 0;
}
```

**Comment by blingenf** [comment]
Thanks for the report. The fact that no similarity is detected for these files is more of a limitation of the algorithm than a bug. It simply means there are no sequences of 25 tokens or more overlapping between the tokenized versions of the two files. For reference, this is what the python files look like in tokenized form:
```python
>>> fp1 = CodeFingerprint("sol2.py", 25, 1)
>>> fp1.filtered_code
'V=[]V=int(input())forVinrange(V):V=int(input())V.V(V)V=[]V=int(input())forVinrange(V):V=int(input())V.V(V)V=set(V)V=[]forVinrange(V):ifV[V]inV:V.V(V[V])print(V)'
>>> fp2 = CodeFingerprint("sol4.py", 25, 1)
>>> fp2.filtered_code
'V=int(input())V=[]forVinrange(V):V.V(int(input()))V=int(input())V=[]forVinrange(V):V.V(int(input()))V=set(V).V(set(V))V=[]forVinrange(V):if(V[V]inV):V.V(V[V])print(V)'
````
You can always increase the sensitivity of the algorithm -- I found that with `noise_threshold = 15` and `guarantee_threshold = 15` copydetect reported a similarity of around 50% for those two files. However, using lower thresholds will also increase the false positive rate. I would recommend experimenting with the threshold a bit (unless you're running into performance issues it's best to adjust them together, i.e. `noise_threshold = guarantee_threshold`).

The crash here is happening because `highlight_overlap` assumes there is at least some similarity to highlight, which in this case there isn't. That is a bug, I should have a fix for it soon.

**Comment by DomrinaV** [comment]
Thank you for the answer and explanation!
